### ISSUE TITLE
Homework 4 Feedback

### ISSUE THREAD

**Issue by kenbod** [YouBarrageTube/YouBarrageTube#1]
Thanks for getting a barebones version of your project up and running. I liked that you have a bunch of user stories but it seems that they were all created by just one person. In the future, please make sure that the workload is balanced across the team. Make the work of each team member *visible*. I will rely on the information I can glean on-line to assess how much work each member did and grade accordingly.

**Comment by YuhanL1n** [comment]
Hi Prof. Ken @kenbod ,

Thanks for your feedback.  But actually we sat together and thought of  those user stories from scratch, then I was just in charge of inputting the stories into the tracking platform. And in future development, we will assign each task to a member so that we cat track everyone's contributions. Based on our plan, the future works will be distributed fairly among us, we will also provide clearer information in it. Sorry for the misunderstanding.
